spring:
  profiles:
    active: dev
  #jpd配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #启用输出日志
    database: mysql #数据库类型#空值，不格式化json数据
  jackson:
    default-property-inclusion: non_null #不将空值格式化
server:
  servlet:
    context-path: /grade