spring:
  profiles:
    active: prod
  #jpd配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #启用输出日志
    database: mysql #数据库类型
  jackson:
    default-property-inclusion: non_null #空值，不格式化json数据
server:
  servlet:
    context-path: /grade