spring:
  datasource:
    url: jdbc:mysql://localhost:4306/score_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: skye
    driver-class-name: com.mysql.cj.jdbc.Driver
  #jpd配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #启用输出日志
    database: mysql #数据库类型
  jackson:
    default-property-inclusion: non_null #空值，不格式化json数据
server:
  servlet:
    context-path: /grade