spring:
  datasource:
    url: jdbc:mysql://localhost:3306/score_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: grade
    password: gradepassword
    driver-class-name: com.mysql.cj.jdbc.Driver